controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - slider_to_cart
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains.slider_to_cart.ff_velocity_scale: 1.0
    #gains.slider_to_cart.p: 1.0
imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: cart_imu_sensor
    frame_id: imu
